name: Push image to ghcr.io

on:
  push:
    branches:
      - '*'

jobs:
  push:
    name: "craftserve-bot"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Get short SHA for tag
        uses: 2428392/gh-truncate-string-action@v1.1.0
        id: truncatedString
        with:
          stringToTruncate: ${{ github.sha }}
          maxLength: 7
      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/craftserve-bot:latest
            ghcr.io/${{ github.repository_owner }}/craftserve-bot:${{ steps.truncatedString.outputs.string }}